### ISSUE TITLE
我很喜欢你写的东西。但是有个BUG

### ISSUE THREAD

**Issue by a0okok** [Cmahjong/ExpandTextView#1]
在实际使用中。我发现。无法给他设置展开文字颜色。设置了也是默认色。但是收起颜色设置生效。希望可以改一下。辛苦

**Comment by yinjinyj** [comment]
老哥，可以啊，我里面有这个属性啊
![image](https://user-images.githubusercontent.com/22814038/45615957-927d0280-baa0-11e8-9ebc-23e642470a9b.png)

**Comment by yinjinyj** [comment]
这是kotlin，你直接setExpandTextColor(int color)就行了

**Comment by Cmahjong** [comment]
我测试时没有问题的
![image](https://user-images.githubusercontent.com/22814038/45658706-2becf880-bb23-11e8-87bb-dd5ecbc8006f.png)
这是我demo的代码，你看一下是不是哪儿有遗漏
不好意思现在才回复，我以为没有人用这个库（如有疑问可以加我qq：1073279000）
thanks

**Comment by Cmahjong** [comment]
谢谢你对这个我的支持

**Comment by Cmahjong** [comment]
没什么问题，我关了哈
