### ISSUE TITLE
效果挺好的，但应该是没处理有行间距的情况

### ISSUE THREAD

**Issue by tmac010sjh** [Cmahjong/ExpandTextView#2]
![1567592382434](https://user-images.githubusercontent.com/12795269/64247122-c155e800-cf40-11e9-98a0-ee3672fea1e9.jpg)

**Comment by Cmahjong** [comment]
这都没有维护了，我当时也就是自己做项目的时候用的，你要用吗？你要用的话我可以按照你的需求改一下

**Comment by Cmahjong** [comment]
这个有个问题就是在recycleview里面的时候，因为布局复用问题，所以你要手动调用一下view.requestLayout()

**Comment by AndMy** [comment]
要用，大佬优化优化吧

**Comment by Cmahjong** [comment]
要用吗？我找个时间改吧改吧，不好意思现在才回复你。非常抱歉，最近比较忙

**Comment by Cmahjong** [comment]
优化了一下，欢迎使用

**Comment by Cmahjong** [comment]
@AndMy
